language: elixir

env:
  global:
    - ORIENTDB_USER=root
    - ORIENTDB_PASS=root
    - ORIENTDB_CACERTFILE="$(pwd)/ci/orientdb.pem"
  matrix:
    - ORIENTDB_VERSION="3.0.0-SNAPSHOT"
    - ORIENTDB_VERSION="2.2.14-SNAPSHOT"
    - ORIENTDB_VERSION="2.2.13"
    - ORIENTDB_VERSION="2.2.12"
    - ORIENTDB_VERSION="2.2.10"
    - ORIENTDB_VERSION="2.2.9"

elixir:
  - 1.2.6

otp_release:
  - 18.3

# We want to use Java 8 because of some error with missing crypto algorithms in
# Java 7.
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x ./ci/ci.sh
  - wget https://raw.githubusercontent.com/michaelklishin/jdk_switcher/master/jdk_switcher.sh && . ./jdk_switcher.sh
  - jdk_switcher use oraclejdk8
  - ./ci/ci.sh
  - export PATH="$(pwd)/tmp:$PATH"

script:
  - mix test.all
